name: lunarestate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
# for android
# version: 1.0.1+2
# for ios
version: 1.0.0+1
# using diffrent version code bcz android version of this app is +1 version from ios
environment:
  sdk: ">=2.18.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animated_bottom_navigation_bar: ^1.1.0
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.0.2
  bot_toast: ^4.0.3
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  eva_icons_flutter: ^3.1.0
  floading: ^2.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.11
  flutter_rating_stars: ^1.0.3+4
  flutter_test:
    sdk: flutter
  flutter_translate: ^4.0.3
  font_awesome_flutter: ^10.2.1
  fullscreen: ^1.0.3
  http: ^0.13.5
  http_parser: ^4.0.2
  image_picker: ^0.8.6
  intl: ^0.17.0
  lecle_flutter_absolute_path: ^0.0.2+1
  multi_image_picker_view: ^0.0.6
  multiple_images_picker: ^1.0.1
  page_transition: ^2.0.9

  photo_view: ^0.14.0
  pin_code_fields: ^7.4.0
  provider: ^6.0.4
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sizer: ^2.0.15
  url_launcher: ^6.1.6
  video_player: ^2.4.7

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/appIcon.jpg"
flutter_native_splash:
  image: "assets/images/tower.jpg"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RocknRollOne
      fonts:
        - asset: assets/fonts/RocknRollOne-Regular.ttf
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Medium.ttf
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
    - family: PTSans
      fonts:
        - asset: assets/fonts/PTSans-BoldItalic.ttf
        - asset: assets/fonts/PTSans-Bold.ttf
        - asset: assets/fonts/PTSans-Italic.ttf
        - asset: assets/fonts/PTSans-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
